import type { VideoSource } from '@/lib/types';

export const PREMIUM_SOURCES: VideoSource[] = [
  // 以下為 Premium 片源
    { "id": "kkxiezhenziyuan", "name": "KK写真资源", "baseUrl": "https://kkzy.me/api.php/provide/vod", "group": "premium", "enabled": true, "priority": 23, "searchPath": "", "detailPath": "" },
    { "id": "91md", "name": "91md", "baseUrl": "http://bt4.cc/api.php/provide/vod/from/mdm3u8", "group": "premium", "enabled": true, "priority": 24, "searchPath": "", "detailPath": "" },
    { "id": "siwaziyuan", "name": "丝袜资源", "baseUrl": "https://siwazyw.cc/api.php/provide/vod", "group": "premium", "enabled": true, "priority": 25, "searchPath": "", "detailPath": "" },
    { "id": "mangguoziyuan", "name": "芒果资源", "baseUrl": "https://mgzyz1.com/api.php/provide/vod", "group": "premium", "enabled": true, "priority": 26, "searchPath": "", "detailPath": "" },
    { "id": "shuimitao", "name": "水蜜桃", "baseUrl": "http://51smt4.xyz/api.php/provide/vod", "group": "premium", "enabled": true, "priority": 27, "searchPath": "", "detailPath": "" },
    { "id": "xiuseziyuan", "name": "秀色资源", "baseUrl": "https://api.xiuseapi.com/api.php/provide/vod", "group": "premium", "enabled": true, "priority": 28, "searchPath": "", "detailPath": "" },
    { "id": "tantanziyuan", "name": "探探资源", "baseUrl": "https://apittzy.com/api.php/provide/vod", "group": "premium", "enabled": true, "priority": 29, "searchPath": "", "detailPath": "" },
    { "id": "sewoziyuan", "name": "色窝资源", "baseUrl": "https://sewozyapi.com/api.php/provide/vod", "group": "premium", "enabled": true, "priority": 30, "searchPath": "", "detailPath": "" },
    { "id": "yinwoziyuan", "name": "淫窝资源", "baseUrl": "https://api.yinwoapi.com/api.php/provide/vod", "group": "premium", "enabled": true, "priority": 31, "searchPath": "", "detailPath": "" },
    { "id": "sediaosiziyuan", "name": "色屌丝资源", "baseUrl": "http://sdszyapi.com/home/cjapi/asbb/mc10/vod", "group": "premium", "enabled": true, "priority": 32, "searchPath": "", "detailPath": "" },
    { "id": "xiaojiejieziyuan", "name": "小姐姐资源", "baseUrl": "https://xjjzyapi.com/home/cjapi/askl/mc10/vod", "group": "premium", "enabled": true, "priority": 33, "searchPath": "", "detailPath": "" },
    { "id": "52avav", "name": "52AVAV", "baseUrl": "https://52zyapi.com/home/cjapi/asda/mc10/vod", "group": "premium", "enabled": true, "priority": 34, "searchPath": "", "detailPath": "" },
    { "id": "woyaopapa", "name": "我要啪啪", "baseUrl": "http://www.caiji21.com/home/cjapi/klkl/mc10/vod", "group": "premium", "enabled": true, "priority": 35, "searchPath": "", "detailPath": "" },
    { "id": "avjizhongyin", "name": "AV集中淫", "baseUrl": "https://www.caiji22.com/home/cjapi/klp0/mc10/vod", "group": "premium", "enabled": true, "priority": 36, "searchPath": "", "detailPath": "" },
    { "id": "yeyeluziyuan", "name": "夜夜撸资源", "baseUrl": "https://www.caiji23.com/home/cjapi/kls6/mc10/vod", "group": "premium", "enabled": true, "priority": 37, "searchPath": "", "detailPath": "" },
    { "id": "dadiaosiziyuan", "name": "大屌丝资源", "baseUrl": "http://www.caiji24.com/home/cjapi/p0d2/mc10/vod", "group": "premium", "enabled": true, "priority": 38, "searchPath": "", "detailPath": "" },
    { "id": "mimiziyuan", "name": "咪咪资源", "baseUrl": "http://www.caiji25.com/home/cjapi/p0as/mc10/vod", "group": "premium", "enabled": true, "priority": 39, "searchPath": "", "detailPath": "" },
    { "id": "baoyuav", "name": "鲍鱼AV", "baseUrl": "http://caiji26.com/home/cjapi/p0g8/mc10/vod", "group": "premium", "enabled": true, "priority": 40, "searchPath": "", "detailPath": "" },
    { "id": "jinggongchangziyuan", "name": "精工厂资源", "baseUrl": "https://jgczyapi.com/home/cjapi/kld2/mc10/vod", "group": "premium", "enabled": true, "priority": 41, "searchPath": "", "detailPath": "" },
    { "id": "diandianyule", "name": "点点娱乐", "baseUrl": "https://xx55zyapi.com/home/cjapi/ascf/mc10/vod", "group": "premium", "enabled": true, "priority": 42, "searchPath": "", "detailPath": "" },
    { "id": "dammziyuan", "name": "大MM资源", "baseUrl": "https://www.dmmapi.com/home/cjapi/asd2c7/mc10/vod", "group": "premium", "enabled": true, "priority": 43, "searchPath": "", "detailPath": "" },
    { "id": "huangguatvziyuan", "name": "黄瓜TV资源", "baseUrl": "https://www.caiji10.com/home/cjapi/cfs6/mc10/vod", "group": "premium", "enabled": true, "priority": 44, "searchPath": "", "detailPath": "" },
    { "id": "kuaiboheziziyuan", "name": "快播盒子资源", "baseUrl": "https://www.caiji09.com/home/cjapi/cfp0/mc10/vod", "group": "premium", "enabled": true, "priority": 45, "searchPath": "", "detailPath": "" },
    { "id": "ribenavzaixian", "name": "日本AV在线", "baseUrl": "https://www.caiji07.com/home/cjapi/cfcf/mc10/vod", "group": "premium", "enabled": true, "priority": 46, "searchPath": "", "detailPath": "" },
    { "id": "jiujiurezaixian", "name": "久久热在线", "baseUrl": "https://www.caiji06.com/home/cjapi/cfbb/mc10/vod", "group": "premium", "enabled": true, "priority": 47, "searchPath": "", "detailPath": "" },
    { "id": "qingqingcaoshipin", "name": "青青草视频", "baseUrl": "https://www.caiji05.com/home/cjapi/cfda/mc10/vod", "group": "premium", "enabled": true, "priority": 48, "searchPath": "", "detailPath": "" },
    { "id": "madoushipin", "name": "麻豆视频", "baseUrl": "https://www.caiji04.com/home/cjapi/cfc7/mc10/vod", "group": "premium", "enabled": true, "priority": 49, "searchPath": "", "detailPath": "" },
    { "id": "yibendaoziyuan", "name": "一本道资源", "baseUrl": "https://www.caiji03.com/home/cjapi/cfg8/mc10/vod", "group": "premium", "enabled": true, "priority": 50, "searchPath": "", "detailPath": "" },
    { "id": "caoliushipin", "name": "草榴视频", "baseUrl": "https://www.caiji02.com/home/cjapi/cfas/mc10/vod", "group": "premium", "enabled": true, "priority": 51, "searchPath": "", "detailPath": "" },
    { "id": "yazhouchengrenzaixian", "name": "亚洲成人在线", "baseUrl": "https://www.caiji01.com/home/cjapi/cfd2/mc10/vod", "group": "premium", "enabled": true, "priority": 52, "searchPath": "", "detailPath": "" },
    { "id": "99ziyuan", "name": "99资源", "baseUrl": "http://99zy.pw/api.php/provide/vod", "group": "premium", "enabled": true, "priority": 53, "searchPath": "", "detailPath": "" },
    { "id": "chihanduizhang", "name": "痴汉队长", "baseUrl": "https://javcaptain.com/api.php/provide/vod", "group": "premium", "enabled": true, "priority": 54, "searchPath": "", "detailPath": "" },
    { "id": "douyinshipin", "name": "抖阴视频", "baseUrl": "https://www.888dav.com/api.php/provide/vod", "group": "premium", "enabled": true, "priority": 55, "searchPath": "", "detailPath": "" },
    { "id": "madoushipin2", "name": "麻豆视频2", "baseUrl": "https://madouse.la/api.php/provide/vod", "group": "premium", "enabled": true, "priority": 56, "searchPath": "", "detailPath": "" },
    { "id": "91madou", "name": "91麻豆", "baseUrl": "https://91md.me/api.php/provide/vod", "group": "premium", "enabled": true, "priority": 57, "searchPath": "", "detailPath": "" },
    { "id": "aicaoziyuan", "name": "爱操资源", "baseUrl": "https://aicaozy.com/api.php/provide/vod", "group": "premium", "enabled": true, "priority": 58, "searchPath": "", "detailPath": "" },
    { "id": "langchaoziyuan", "name": "浪潮资源", "baseUrl": "http://langchaozy6.com/api.php/provide/vod", "group": "premium", "enabled": true, "priority": 59, "searchPath": "", "detailPath": "" },
    { "id": "suboziyuan", "name": "速播资源", "baseUrl": "https://api.suboapi.com/api.php/provide/vod", "group": "premium", "enabled": true, "priority": 60, "searchPath": "", "detailPath": "" },
    { "id": "kudouziyuan", "name": "酷豆资源", "baseUrl": "https://kudouzy.com/api.php/provide/vod", "group": "premium", "enabled": true, "priority": 61, "searchPath": "", "detailPath": "" },
    { "id": "kudou2", "name": "酷豆2", "baseUrl": "https://api.kdapi.info/api.php/provide/vod", "group": "premium", "enabled": true, "priority": 62, "searchPath": "", "detailPath": "" },
    { "id": "kulunli", "name": "酷伦理", "baseUrl": "https://api.kudian70.com/api.php/provide/vod", "group": "premium", "enabled": true, "priority": 63, "searchPath": "", "detailPath": "" },
    { "id": "yingkuziyuan", "name": "影库资源", "baseUrl": "https://api.ykapi.net/api.php/provide/vod", "group": "premium", "enabled": true, "priority": 64, "searchPath": "", "detailPath": "" },
    { "id": "wanyingse", "name": "万影色", "baseUrl": "https://wanying4.com/api.php/provide/vod", "group": "premium", "enabled": true, "priority": 65, "searchPath": "", "detailPath": "" },
    { "id": "yinlongziyuan", "name": "银龙资源", "baseUrl": "https://yinlong.tv/api.php/provide/vod", "group": "premium", "enabled": true, "priority": 66, "searchPath": "", "detailPath": "" },
    { "id": "aiboziyuan", "name": "爱播资源", "baseUrl": "https://cj.apiabzy.com/api.php/provide/vod", "group": "premium", "enabled": true, "priority": 67, "searchPath": "", "detailPath": "" },
    { "id": "ckziyuan", "name": "CK资源", "baseUrl": "http://www.feifei67.com/api.php/provide/vod", "group": "premium", "enabled": true, "priority": 68, "searchPath": "", "detailPath": "" },
    { "id": "laoyaziyuan", "name": "老鸭资源", "baseUrl": "https://api.apilyzy.com/api.php/provide/vod", "group": "premium", "enabled": true, "priority": 69, "searchPath": "", "detailPath": "" },
    { "id": "huajiaoziyuan", "name": "花椒资源", "baseUrl": "https://apihjzy.com/api.php/provide/vod", "group": "premium", "enabled": true, "priority": 70, "searchPath": "", "detailPath": "" },
    { "id": "lajiaoziyuan", "name": "辣椒资源", "baseUrl": "https://apilj.com/api.php/provide/vod", "group": "premium", "enabled": true, "priority": 71, "searchPath": "", "detailPath": "" },
    { "id": "leboziyuan", "name": "乐播资源", "baseUrl": "https://lbapi9.com/api.php/provide/vod", "group": "premium", "enabled": true, "priority": 72, "searchPath": "", "detailPath": "" },
    { "id": "jializiyuan", "name": "佳丽资源", "baseUrl": "http://www.jializyzapi.com/api.php/provide/vod", "group": "premium", "enabled": true, "priority": 73, "searchPath": "", "detailPath": "" },
    { "id": "fanhaoziyuan", "name": "番号资源", "baseUrl": "http://fhapi9.com/api.php/provide/vod", "group": "premium", "enabled": true, "priority": 74, "searchPath": "", "detailPath": "" },
    { "id": "shayuziyuan", "name": "鲨鱼资源", "baseUrl": "https://shayuapi.com/api.php/provide/vod", "group": "premium", "enabled": true, "priority": 75, "searchPath": "", "detailPath": "" },
];
